from .group import Group
from typing import Iterator

class Groups:
    def new(self) -> Group:
        ...
    def new_physics(self) -> Group:
        ...
    def __iter__(self) -> Iterator[Group]:
        ...
    def __next__(self) -> Group:
        ...
