class Images:
    def new_from_file(self, path: str) -> Images:
        ...
    def width(self) -> int:
        ...
    def height(self) -> int:
        ...
    def is_external(self) -> bool:
        ...
    def is_embedded(self) -> bool:
        ...
    def embed(self, path: str):
        ...
    def save(self, path: str):
        ...
    def __iter__(self):
        ...
    def __next__(self):
        ...
