from typing import Optional
import numpy

from .quads import Quads

class Layers:
    tiles: numpy.ndarray
    image: Optional[int]
    quads: Quads
    def new_quads(self) -> Layers:
        ...
    def new_sounds(self) -> Layers:
        ...
    def new_tiles(self, width: int, height: int) -> Layers:
        ...
    def new_game(self, width: int, height: int) -> Layers:
        ...
    def new_physics(self, kind: str) -> Layers:
        ...
    def width(self) -> int:
        ...
    def height(self) -> int:
        ...
    def kind(self) -> str:
        ...
    def to_mesh(self) -> tuple:
        ...
    def __iter__(self):
        ...
    def __next__(self):
        ...
